### ISSUE TITLE
Fix rpm version

### ISSUE THREAD

**Issue by jonyrock** [REC-SPb-ETU/Gpstk#15]
It is `2.3.2` now and it should be fixed

**Comment by eugenyk** [comment]
Fixed in https://github.com/REC-SPb-ETU/Gpstk/commit/c3f9dc857d3ddf4f83e5b479397614505ac468b5 The best way is to make a version.in template to generate version.h during CMake prepare

**Comment by eugenyk** [comment]
There is no need to make version.in because no "version" is used in project sources
