### ISSUE TITLE
Gpstk & rpm

### ISSUE THREAD

**Issue by jonyrock** [REC-SPb-ETU/Gpstk#8]
Just to log here process.

**Comment by jonyrock** [comment]
https://github.com/jonyrock/Gpstk/blob/38f355122a8012f02eec9cf62d376b4e04294869/ref/build/ftjam-2.5.2-gpstk/Jamfile

**Comment by eugenyk** [comment]
I think there is no need to use Jam like boost - CPack is enough. Commit reviewed, comments available

**Comment by eugenyk** [comment]
All CPack's available things are ready, rpm tested on Fedora 19, OpenSUSE 13.2. Moreover deb-package tested on Ubuntu 12.4
